# Generated by Django 4.0.6 on 2022-07-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlastQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_sequence', models.CharField(max_length=4096)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.CharField(max_length=270)),
                ('protein_id', models.CharField(max_length=270)),
                ('subseq_start', models.IntegerField()),
                ('subseq_end', models.IntegerField()),
                ('dna_sequence', models.CharField(max_length=4096)),
                ('locus_tag', models.CharField(max_length=270)),
                ('hsp_bit_score', models.FloatField()),
                ('orig_query', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ginkgo.blastquery')),
            ],
        ),
    ]
