version: '3'

services:
  react:
    build: ./frontend/
    image: react-app-image
    ports:
      - "80:3000"
  django:
    build: ./
    image: django-api-image
    tty: true
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
