version: '3'

services:
  react:
    build: ./frontend/
    image: react-app-image
    ports:
      - "3000:3000"
  django:
    build: ./
    image: django-api-image
    tty: true
    ports:
      - "8000:8000"